import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControlLabel, Switch, IconButton, Alert } from '@mui/material';
import { ArrowBack, Save } from '@mui/icons-material';
import { Controller } from 'react-hook-form';
import { useAppDispatch } from '../app/hooks';
import { addLocalProduct } from '../features/products/productSlice';
import { useCreateProductMutation } from '../services/productApi';
import { FormField } from '../components/common/FormField';
import { ToastNotification } from '../components/common/ToastNotification';
import { useToast, useSocket, useProductForm } from '../hooks';
import { type ProductFormData } from '../utils/validation';
import type { CreateProductInput } from '../types';
import { GradientButton, ElevatedCard, GradientText, FlexRow } from '../components/styled';

export const CreateProductPage = () => {
	const navigate = useNavigate();
	const dispatch = useAppDispatch();
	const { toast, showSuccess, showError, closeToast } = useToast();
	const { emitProductCreated } = useSocket();
	const [createProduct] = useCreateProductMutation();

	const { control, handleSubmit, isSubmitting } = useProductForm();

	const onSubmit = async (data: ProductFormData) => {
		try {
			const productInput: CreateProductInput = {
				title: data.title,
				price: data.price,
				description: data.description,
				category: data.category || undefined,
				image: data.image || undefined,
				published: data.published,
			};

			await createProduct(productInput).unwrap();

			dispatch(addLocalProduct(productInput));

			emitProductCreated({
				...productInput,
				id: '', // Will be generated by slice
				createdAt: new Date().toISOString(),
			});

			showSuccess('Product created successfully!');
			setTimeout(() => navigate('/products?tab=my'), 1500);
		} catch (error) {
			showError('Failed to create product. Please try again.');
			console.error('Error creating product:', error);
		}
	};

	return (
		<Box sx={{ maxWidth: 800, mx: 'auto', width: '100%' }}>
			<FlexRow sx={{ mb: 3 }}>
				<IconButton onClick={() => navigate(-1)}>
					<ArrowBack />
				</IconButton>
				<GradientText variant='h4' component='h1'>
					Create New Product
				</GradientText>
			</FlexRow>

			<ElevatedCard sx={{ p: 3 }}>
				<Alert severity='info' sx={{ mb: 2, py: 1 }}>
					<Typography variant='caption' sx={{ display: 'block', mb: 0.5, fontWeight: 600 }}>
						Validation Rules:
					</Typography>
					<Typography variant='caption' sx={{ fontSize: '0.7rem', lineHeight: 1.4 }}>
						• Title: 3-100 chars • Price: $0.01-$999,999.99
						<br />
						• Description: 10-500 chars • Category: 2-50 chars (optional)
						<br />• Image: Valid URL (optional)
					</Typography>
				</Alert>

				<form onSubmit={handleSubmit(onSubmit)}>
					<Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
						<FormField name='title' control={control} label='Title' required placeholder='Amazing Product' />

						<FormField
							name='price'
							control={control}
							label='Price'
							type='number'
							required
							placeholder='19.99'
							inputProps={{ step: '0.01', min: '0.01', max: '999999.99' }}
						/>

						<FormField
							name='description'
							control={control}
							label='Description'
							required
							multiline
							rows={4}
							placeholder='Detailed product description...'
						/>

						<FormField name='category' control={control} label='Category' placeholder='Electronics' />

						<FormField
							name='image'
							control={control}
							label='Image URL'
							placeholder='https://example.com/image.jpg'
						/>

						<Controller
							name='published'
							control={control}
							render={({ field }) => (
								<FormControlLabel control={<Switch {...field} checked={field.value} />} label='Published' />
							)}
						/>

						<FlexRow sx={{ justifyContent: 'flex-end' }}>
							<GradientButton variant='outlined' onClick={() => navigate(-1)} disabled={isSubmitting}>
								Cancel
							</GradientButton>
							<GradientButton type='submit' disabled={isSubmitting} startIcon={<Save />}>
								{isSubmitting ? 'Creating...' : 'Create Product'}
							</GradientButton>
						</FlexRow>
					</Box>
				</form>
			</ElevatedCard>

			<ToastNotification open={toast.open} message={toast.message} severity={toast.severity} onClose={closeToast} />
		</Box>
	);
};
